rosatom_dobro/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

rosatom_dobro/map/urls.py
from django.urls import path
from . import views

app_name = 'map'

urlpatterns = [
    path('', views.map_view, name='map_view'),
]

rosatom_dobro/rosatom_dobro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('nko/', include('nko.urls')),
    path('knowledge/', include('knowledge_base.urls')),
    path('events/', include('events.urls')),
    path('news/', include('news.urls')),
    path('users/', include('users.urls')),
    path('map/', include('map.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Админка сайта «Добрые дела Росатома»'

rosatom_dobro/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # Аутентификация волонтёров
    path('login/volunteer/', views.volunteer_login, name='volunteer_login'),
    path('register/volunteer/', views.volunteer_register, name='register_volunteer'),

    # Аутентификация НКО
    path('login/nko/', views.nko_login, name='nko_login'),
    path('register/nko/', views.nko_register, name='register_nko'),

    # Профиль
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('logout/', views.custom_logout, name='logout'),
]

rosatom_dobro/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = (
        ('volunteer', 'Волонтер'),
        ('nko', 'НКО'),
        ('admin', 'Администратор'),
    )

    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES, default='volunteer')
    email = models.EmailField(unique=True, max_length=254, verbose_name='E-mail', db_index=True)
    age = models.IntegerField(blank=True, null=True)
    city = models.ForeignKey('nko.City', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.username} ({self.email})"

rosatom_dobro/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser
from nko.models import City, Category, NKO


class VolunteerRegistrationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label='Email',
        widget=forms.EmailInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите ваш email'
        })
    )
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Придумайте имя пользователя'
        })
    )
    first_name = forms.CharField(
        required=True,
        label='Имя',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Ваше имя',
        })
    )
    last_name = forms.CharField(
        required=True,
        label='Фамилия',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Ваша фамилия'
        })
    )
    age = forms.IntegerField(
        required=True,
        label='Возраст',
        widget=forms.NumberInput(attrs={
            'class': 'form-input',
            'placeholder': 'Ваш возраст',
            'min': '14',
            'max': '100'
        })
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.all(),
        required=True,
        label='Город',
        widget=forms.Select(attrs={'class': 'form-select'}),
        empty_label="Выберите город"
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'age', 'city', 'password1', 'password2']
        labels = {
            'password1': 'Пароль',
            'password2': 'Подтверждение пароля',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Придумайте пароль'})
        self.fields['password2'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Повторите пароль'})

    def save(self, commit=True):
        user = super().save(commit=False)
        user.user_type = 'volunteer'
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class NKORegistrationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label='Email организации',
        widget=forms.EmailInput(attrs={
            'class': 'form-input',
            'placeholder': 'Email организации'
        })
    )
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Имя пользователя для входа'
        })
    )

    # Поля для модели NKO
    name = forms.CharField(
        max_length=200,
        label='Название НКО',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Название НКО'
        })
    )
    description = forms.CharField(
        label='Описание деятельности',
        widget=forms.Textarea(attrs={
            'class': 'form-input',
            'placeholder': 'Подробное описание деятельности',
            'rows': 4
        })
    )
    short_description = forms.CharField(
        max_length=300,
        label='Краткое описание',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Краткое описание (2-3 предложения)'
        })
    )
    logo = forms.ImageField(
        required=False,
        label='Логотип организации',
        widget=forms.FileInput(attrs={
            'class': 'form-input'
        })
    )
    address = forms.CharField(
        required=False,
        label='Адрес',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Адрес организации'
        })
    )
    website = forms.URLField(
        required=False,
        label='Веб-сайт',
        widget=forms.URLInput(attrs={
            'class': 'form-input',
            'placeholder': 'Сайт организации'
        })
    )
    vk_link = forms.URLField(
        required=False,
        label='ВКонтакте',
        widget=forms.URLInput(attrs={
            'class': 'form-input',
            'placeholder': 'Ссылка на ВКонтакте'
        })
    )
    telegram_link = forms.URLField(
        required=False,
        label='Telegram',
        widget=forms.URLInput(attrs={
            'class': 'form-input',
            'placeholder': 'Ссылка на Telegram'
        })
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.all(),
        required=True,
        label='Город',
        widget=forms.Select(attrs={'class': 'form-select'}),
        empty_label="Выберите город"
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=True,
        label='Категория деятельности',
        widget=forms.Select(attrs={'class': 'form-select'}),
        empty_label="Выберите категорию"
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']
        labels = {
            'password1': 'Пароль',
            'password2': 'Подтверждение пароля',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Придумайте пароль'})
        self.fields['password2'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Повторите пароль'})

    def save(self, commit=True):
        user = super().save(commit=False)
        user.user_type = 'nko'
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
            # Создаем запись НКО
            nko = NKO.objects.create(
                user=user,
                name=self.cleaned_data['name'],
                description=self.cleaned_data['description'],
                short_description=self.cleaned_data['short_description'],
                logo=self.cleaned_data['logo'],
                address=self.cleaned_data['address'],
                website=self.cleaned_data['website'],
                vk_link=self.cleaned_data['vk_link'],
                telegram_link=self.cleaned_data['telegram_link'],
                city=self.cleaned_data['city'],
                category=self.cleaned_data['category']
            )

        return user


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Имя пользователя'
        })
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Пароль'
        })
    )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'age', 'city']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Email',
            'age': 'Возраст',
            'city': 'Город',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Ваше имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Ваша фамилия'}),
            'email': forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'Ваш email'}),
            'age': forms.NumberInput(
                attrs={'class': 'form-input', 'placeholder': 'Ваш возраст', 'min': '14', 'max': '100'}),
            'city': forms.Select(attrs={'class': 'form-select'}),
        }


class NKOUpdateForm(forms.ModelForm):
    class Meta:
        model = NKO
        fields = ['name', 'description', 'short_description', 'logo', 'address', 'website', 'vk_link', 'telegram_link',
                  'city', 'category']
        labels = {
            'name': 'Название НКО',
            'description': 'Описание деятельности',
            'short_description': 'Краткое описание',
            'logo': 'Логотип организации',
            'address': 'Адрес',
            'website': 'Веб-сайт',
            'vk_link': 'ВКонтакте',
            'telegram_link': 'Telegram',
            'city': 'Город',
            'category': 'Категория деятельности',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Название организации'}),
            'description': forms.Textarea(
                attrs={'class': 'form-input', 'rows': 4, 'placeholder': 'Подробное описание деятельности'}),
            'short_description': forms.TextInput(
                attrs={'class': 'form-input', 'placeholder': 'Краткое описание (2-3 предложения)'}),
            'logo': forms.FileInput(attrs={'class': 'form-input'}),
            'address': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Адрес организации'}),
            'website': forms.URLInput(attrs={'class': 'form-input', 'placeholder': 'https://example.com'}),
            'vk_link': forms.URLInput(attrs={'class': 'form-input', 'placeholder': 'https://vk.com/yourpage'}),
            'telegram_link': forms.URLInput(attrs={'class': 'form-input', 'placeholder': 'https://t.me/yourchannel'}),
            'city': forms.Select(attrs={'class': 'form-select'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }

rosatom_dobro/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from .forms import (
    VolunteerRegistrationForm, NKORegistrationForm,
    CustomAuthenticationForm, UserUpdateForm, NKOUpdateForm
)
from .models import CustomUser
from nko.models import NKO


def volunteer_login(request):
    if request.user.is_authenticated:
        return redirect('users:profile')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None and user.user_type == 'volunteer':
                login(request, user)
                # messages.success(request, f'Добро пожаловать, {user.username}!')
                next_url = request.GET.get('next', 'users:profile')
                return redirect(next_url)
            else:
                messages.error(request, 'Неверные данные для входа или вы не волонтер')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки в форме')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
        'user_type': 'volunteer',
        'title': 'Вход для волонтёров'
    }
    return render(request, 'users/login.html', context)


def nko_login(request):
    if request.user.is_authenticated:
        return redirect('users:profile')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None and user.user_type == 'nko':
                login(request, user)
                # messages.success(request, f'Добро пожаловать, {user.nko.name}!')
                next_url = request.GET.get('next', 'users:profile')
                return redirect(next_url)
            else:
                messages.error(request, 'Неверные данные для входа или вы не НКО')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки в форме')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
        'user_type': 'nko',
        'title': 'Вход для НКО'
    }
    return render(request, 'users/login.html', context)


def volunteer_register(request):
    if request.user.is_authenticated:
        return redirect('users:profile')

    if request.method == 'POST':
        form = VolunteerRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # messages.success(request, 'Регистрация прошла успешно! Добро пожаловать!')
            return redirect('users:profile')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки в форме')
    else:
        form = VolunteerRegistrationForm()

    context = {
        'form': form,
        'user_type': 'volunteer',
        'title': 'Регистрация волонтёра'
    }
    return render(request, 'users/register.html', context)


def nko_register(request):
    if request.user.is_authenticated:
        return redirect('users:profile')

    if request.method == 'POST':
        form = NKORegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # messages.success(request, 'Регистрация НКО прошла успешно! Ожидайте подтверждения администратора.')
            return redirect('users:profile')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки в форме')
    else:
        form = NKORegistrationForm()

    context = {
        'form': form,
        'user_type': 'nko',
        'title': 'Регистрация НКО'
    }
    return render(request, 'users/register.html', context)


@login_required
def profile(request):
    context = {}

    if request.user.user_type == 'nko':
        try:
            nko = NKO.objects.get(user=request.user)
            context['nko'] = nko
        except NKO.DoesNotExist:
            messages.error(request, 'Профиль НКО не найден')

    return render(request, 'users/profile.html', context)


@login_required
def profile_edit(request):
    if request.method == 'POST':
        if request.user.user_type == 'volunteer':
            form = UserUpdateForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                messages.success(request, 'Профиль успешно обновлен!')
                return redirect('users:profile')
        else:  # НКО
            nko = get_object_or_404(NKO, user=request.user)
            form = NKOUpdateForm(request.POST, request.FILES, instance=nko)
            if form.is_valid():
                form.save()
                messages.success(request, 'Профиль НКО успешно обновлен!')
                return redirect('users:profile')
    else:
        if request.user.user_type == 'volunteer':
            form = UserUpdateForm(instance=request.user)
        else:
            nko = get_object_or_404(NKO, user=request.user)
            form = NKOUpdateForm(instance=nko)

    context = {
        'form': form,
        'nko': getattr(request.user, 'nko', None) if request.user.user_type == 'nko' else None
    }
    return render(request, 'users/profile_edit.html', context)


@login_required
def custom_logout(request):
    logout(request)
    # messages.success(request, 'Вы успешно вышли из системы')
    return redirect('main:home')

rosatom_dobro/templates/users/auth_base.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<style>
    .auth-container {
        min-height: calc(100vh - 140px);
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 2rem;
        background: linear-gradient(135deg, var(--primary-light-blue) 0%, var(--white) 100%);
    }

    .auth-card {
        background: var(--white);
        padding: 3rem;
        border-radius: 15px;
        box-shadow: 0 10px 30px rgba(0, 102, 204, 0.1);
        width: 100%;
        max-width: 500px;
        animation: slideUp 0.5s ease;
    }

    .auth-header {
        text-align: center;
        margin-bottom: 2rem;
    }

    .auth-icon {
        font-size: 3rem;
        color: var(--primary-blue);
        margin-bottom: 1rem;
    }

    .auth-title {
        color: var(--text-color);
        margin-bottom: 0.5rem;
        font-weight: 600;
    }

    .auth-subtitle {
        color: var(--dark-gray);
        opacity: 0.7;
    }

    .form-group {
        margin-bottom: 1.5rem;
    }

    .form-label {
        display: block;
        margin-bottom: 0.5rem;
        font-weight: 500;
        color: var(--text-color);
    }

    .form-input, .form-select {
        width: 100%;
        padding: 0.75rem 1rem;
        border: 2px solid var(--medium-gray);
        border-radius: 8px;
        font-size: 1rem;
        transition: var(--transition);
        background: var(--white);
    }

    .form-input:focus, .form-select:focus {
        outline: none;
        border-color: var(--primary-blue);
        box-shadow: 0 0 0 3px rgba(0, 102, 204, 0.1);
    }

    .form-input::placeholder {
        color: #a0a0a0;
    }

    .error-list {
        color: #e74c3c;
        font-size: 0.9rem;
        margin-top: 0.25rem;
    }

    .error-list li {
        margin-bottom: 0.25rem;
    }

    .auth-btn {
        width: 100%;
        padding: 1rem;
        background: var(--primary-blue);
        color: var(--white);
        border: none;
        border-radius: 8px;
        font-size: 1rem;
        font-weight: 600;
        cursor: pointer;
        transition: var(--transition);
        margin-bottom: 1.5rem;
    }

    .auth-btn:hover {
        background: var(--primary-dark-blue);
        transform: translateY(-2px);
        box-shadow: 0 6px 20px rgba(0, 102, 204, 0.3);
    }

    .auth-links {
        text-align: center;
        margin-top: 1.5rem;
        padding-top: 1.5rem;
        border-top: 1px solid var(--medium-gray);
    }

    .auth-link {
        color: var(--primary-blue);
        text-decoration: none;
        margin: 0 0.5rem;
        font-weight: 500;
        transition: var(--transition);
    }

    .auth-link:hover {
        color: var(--primary-dark-blue);
        text-decoration: underline;
    }

    .user-type-badge {
        display: inline-block;
        padding: 0.25rem 0.75rem;
        border-radius: 15px;
        font-size: 0.8rem;
        font-weight: 600;
        margin-left: 0.5rem;
    }

    .badge-volunteer {
        background: var(--primary-light-blue);
        color: var(--primary-blue);
    }

    .badge-nko {
        background: #e8f5e8;
        color: #27ae60;
    }

    @media (max-width: 768px) {
        .auth-card {
            padding: 2rem;
            margin: 1rem;
        }
    }
</style>
{% endblock %}

{% block content %}
<div class="auth-container">
    <div class="auth-card">
        {% block auth_content %}
        {% endblock %}
    </div>
</div>
{% endblock %}

rosatom_dobro/templates/users/login.html
{% extends 'users/auth_base.html' %}
{% load static %}

{% block title %}{{ title }} - Добрые дела Росатома{% endblock %}

{% block auth_content %}
<div class="auth-header">
    <div class="auth-icon">
        {% if user_type == 'volunteer' %}
            <i class="fas fa-user"></i>
        {% else %}
            <i class="fas fa-building"></i>
        {% endif %}
    </div>
    <h1 class="auth-title">{{ title }}</h1>
    <p class="auth-subtitle">
        {% if user_type == 'volunteer' %}
            Войдите в свой аккаунт волонтёра
        {% else %}
            Войдите в аккаунт вашей организации
        {% endif %}
    </p>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" style="
            padding: 1rem;
            margin-bottom: 1rem;
            border-radius: 8px;
            background: {% if message.tags == 'success' %}#d4edda{% else %}#f8d7da{% endif %};
            color: {% if message.tags == 'success' %}#155724{% else %}#721c24{% endif %};
            border: 1px solid {% if message.tags == 'success' %}#c3e6cb{% else %}#f5c6cb{% endif %};
        ">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}

    {% for field in form %}
        <div class="form-group">
            <label class="form-label" for="{{ field.id_for_label }}">
                {{ field.label }}
            </label>
            {{ field }}
            {% if field.errors %}
                <ul class="error-list">
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    {% endfor %}

    <button type="submit" class="auth-btn">
        Войти
    </button>
</form>

<div class="auth-links">
    {% if user_type == 'volunteer' %}
        <p>Нет аккаунта?
            <a href="{% url 'users:register_volunteer' %}" class="auth-link">
                Зарегистрироваться как волонтёр
            </a>
        </p>
        <p>Вы НКО?
            <a href="{% url 'users:nko_login' %}" class="auth-link">
                Войти как НКО
            </a>
        </p>
    {% else %}
        <p>Нет аккаунта?
            <a href="{% url 'users:register_nko' %}" class="auth-link">
                Зарегистрировать НКО
            </a>
        </p>
        <p>Вы волонтёр?
            <a href="{% url 'users:volunteer_login' %}" class="auth-link">
                Войти как волонтёр
            </a>
        </p>
    {% endif %}
    <p>
        <a href="{% url 'main:home' %}" class="auth-link">
            ← Вернуться на главную
        </a>
    </p>
</div>
{% endblock %}

rosatom_dobro/templates/users/register.html
{% extends 'users/auth_base.html' %}
{% load static %}

{% block title %}{{ title }} - Добрые дела Росатома{% endblock %}

{% block auth_content %}
<div class="auth-header">
    <div class="auth-icon">
        {% if user_type == 'volunteer' %}
            <i class="fas fa-user-plus"></i>
        {% else %}
            <i class="fas fa-building"></i>
        {% endif %}
    </div>
    <h1 class="auth-title">{{ title }}</h1>
    <p class="auth-subtitle">
        {% if user_type == 'volunteer' %}
            Присоединяйтесь к сообществу волонтёров
        {% else %}
            Зарегистрируйте вашу организацию на платформе
        {% endif %}
    </p>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" style="
            padding: 1rem;
            margin-bottom: 1rem;
            border-radius: 8px;
            background: {% if message.tags == 'success' %}#d4edda{% else %}#f8d7da{% endif %};
            color: {% if message.tags == 'success' %}#155724{% else %}#721c24{% endif %};
            border: 1px solid {% if message.tags == 'success' %}#c3e6cb{% else %}#f5c6cb{% endif %};
        ">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<form method="post" {% if user_type == 'nko' %}enctype="multipart/form-data"{% endif %}>
    {% csrf_token %}

    {% for field in form %}
        <div class="form-group">
            <label class="form-label" for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}<span style="color: #e74c3c;">*</span>{% endif %}
            </label>
            {{ field }}
            {% if field.help_text %}
                <small style="color: #666; font-size: 0.8rem; display: block; margin-top: 0.25rem;">
                    {{ field.help_text }}
                </small>
            {% endif %}
            {% if field.errors %}
                <ul class="error-list">
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    {% endfor %}

    <button type="submit" class="auth-btn">
        {% if user_type == 'volunteer' %}
            Стать волонтёром
        {% else %}
            Зарегистрировать НКО
        {% endif %}
    </button>
</form>

<div class="auth-links">
    {% if user_type == 'volunteer' %}
        <p>Уже есть аккаунт?
            <a href="{% url 'users:volunteer_login' %}" class="auth-link">
                Войти как волонтёр
            </a>
        </p>
        <p>Вы НКО?
            <a href="{% url 'users:register_nko' %}" class="auth-link">
                Зарегистрировать НКО
            </a>
        </p>
    {% else %}
        <p>Уже есть аккаунт?
            <a href="{% url 'users:nko_login' %}" class="auth-link">
                Войти как НКО
            </a>
        </p>
        <p>Вы волонтёр?
            <a href="{% url 'users:register_volunteer' %}" class="auth-link">
                Стать волонтёром
            </a>
        </p>
    {% endif %}
    <p>
        <a href="{% url 'main:home' %}" class="auth-link">
            ← Вернуться на главную
        </a>
    </p>
</div>
{% endblock %}